version: "3.9"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
    - "4500:80"
    volumes:
    - ./:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - dbdata:/var/lib/mysql
      - ./codeigniternotebook.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codeigniternotebook

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      MYSQL_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"


volumes:
  dbdata:
